name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies for zorkweb.client
        working-directory: ./zorkweb.client
        run: npm ci

      - name: Install Playwright browsers
        working-directory: ./zorkweb.client
        run: npx playwright install --with-deps

      - name: Restore .NET dependencies
        run: dotnet restore

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.nuget/packages
            ./zorkweb.client/node_modules
          key: ${{ runner.os }}-deps-${{ hashFiles('**/packages.lock.json', '**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-deps-

  dotnet-build-and-test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.nuget/packages
          key: ${{ runner.os }}-deps-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Build
        run: dotnet build --no-restore

      - name: .NET tests
        run: dotnet test --no-build --verbosity normal

  playwright-tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            ./zorkweb.client/node_modules
          key: ${{ runner.os }}-deps-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Install Playwright browsers
        working-directory: ./zorkweb.client
        run: npx playwright install --with-deps

      - name: Playwright tests
        working-directory: ./zorkweb.client
        run: npx playwright test

      - name: Upload Playwright test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: zorkweb.client/playwright-report/
          retention-days: 30
